name: Version Update

on:
  workflow_dispatch: # 允许手动触发
    inputs:
      type:
        description: 'Specify the release type (release or snapshot)'
        required: true
        default: 'snapshot'
        type: choice
        options:
          - release
          - snapshot

jobs:
  version-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set execute permissions for ci.sh
        run: chmod +x ./ci.sh

      - name: Run ci.sh
        run: |
          ./ci.sh ${{ github.event.inputs.type }}
          echo "TAG_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Trigger Publish to pub.dev pipeline
        if: success()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/publish.yml/dispatches \
            -d '{"ref":"${TAG_VERSION}"}'

