name: Version Update

on:
  workflow_dispatch: # 允许手动触发
    inputs:
      type:
        description: 'Specify the release type (release or snapshot)'
        required: true
        default: 'snapshot'
        type: choice
        options:
          - release
          - snapshot

jobs:
  version-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set execute permissions for ci.sh
        run: chmod +x ./ci.sh

      - name: Run ci.sh
        run: ./ci.sh ${{ github.event.inputs.type }}

      - name: Push tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git push origin --tags
