name: Publish to pub.dev

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish'
        required: true

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Publish to pub.dev
        run: flutter pub publish --server=https://pub.dartlang.org -f
