name: Publish to pub.dev

on:
  workflow_dispatch: # 允许手动触发
    inputs:
      type:
        description: 'Specify the release type (release or snapshot)'
        required: true
        default: 'snapshot'
        type: choice
        options:
          - release
          - snapshot

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set execute permissions for ci.sh
        run: chmod +x ./ci.sh

      - name: Run ci.sh
        run: ./ci.sh ${{ github.event.inputs.type }}

      - uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Publish to pub.dev
        run: flutter pub publish --server=https://pub.dartlang.org -f
